repos:
  - repo: local
    hooks:
      - id: code-similarity
        name: Code Similarity (add/modify/delete)
        language: system
        pass_filenames: true
        stages: [pre-commit]
        files: '\.(py|java)$'
        exclude: '^code_similarity_tool/'
        entry: bash -lc 'env PYTHONDONTWRITEBYTECODE=1 python -B -m code_similarity_tool.code_similarity --with-deletions "$@"'
